export const medicalProfessional = {
  fullName: "Dr. John Doe",
  initials: "DJD",
  profession: "Hospital Administrator",
};

export const patients = [
  {
    id: "P001",
    initials: "JD",
    name: "John Doe",
    checkInDate: "2024-10-10",
    disease: "Flu",
    appointmentType: "Regular Check-up",
    mode: "In-Person",
    date: "2024-10-10",
    time: "09:00 AM",
    town: "Springfield",
    insured: true,
    age: "30",
    sex: "Male",
    education: "Bachelor's Degree",
    occupation: "Engineer",
    religion: "Christianity",
    maritalStatus: "Married",
    assignedDoctor: {
      name: "Dr. Stella",
      image: "https://randomuser.me/api/portraits/men/3.jpg",
    },
    // New fields for PatientHistory
    primaryDiagnosis: "Acute Viral Infection",
    pastConditions: ["Asthma", "Bronchitis"],
    allergies: ["Peanuts", "Dust"],
    medications: ["Paracetamol", "Cough Syrup"],
    visits: [
      {
        date: "2024-09-10",
        type: "Consultation",
        doctor: "Dr. Stella",
        diagnosis: "Acute Viral Infection",
        medicationPrescribed: ["Paracetamol", "Cough Syrup"],
        notes: "Recommended rest and hydration.",
      },
      {
        date: "2024-08-15",
        type: "Follow-up",
        doctor: "Dr. Stella",
        diagnosis: "Flu",
        medicationPrescribed: ["Paracetamol"],
        notes: "Symptoms improving, no medication adjustments.",
      },
    ],
  },
  {
    id: "P002",
    initials: "JD",
    name: "Jane Doe",
    checkInDate: "2024-10-10",
    disease: "Stomach Ache",
    appointmentType: "Regular Check-up",
    mode: "Online",
    date: "2024-10-10",
    time: "10:30 AM",
    town: "Riverdale",
    insured: false,
    age: "28",
    sex: "Female",
    education: "Master's Degree",
    occupation: "Teacher",
    religion: "Christianity",
    maritalStatus: "Single",
    assignedDoctor: {
      name: "Dr. Emma",
      image: "https://randomuser.me/api/portraits/women/4.jpg",
    },
    // New fields for PatientHistory
    primaryDiagnosis: "Gastroenteritis",
    pastConditions: ["Irritable Bowel Syndrome"],
    allergies: ["Seafood"],
    medications: ["Probiotic", "Antacid"],
    visits: [
      {
        date: "2024-10-01",
        type: "Emergency",
        doctor: "Dr. Emma",
        diagnosis: "Gastroenteritis",
        medicationPrescribed: ["Probiotic", "Antacid"],
        notes: "Acute pain, administered antacid and IV fluids.",
      },
    ],
  },
  {
    id: "P003",
    initials: "MK",
    name: "Michael King",
    checkInDate: "2024-10-11",
    disease: "Cold",
    appointmentType: "Regular Check-up",
    mode: "In-Person",
    date: "2024-10-11",
    time: "11:00 AM",
    town: "Hillside",
    insured: true,
    age: "40",
    sex: "Male",
    education: "High School",
    occupation: "Driver",
    religion: "Islam",
    maritalStatus: "Married",
    assignedDoctor: {
      name: "Dr. John",
      image: "https://randomuser.me/api/portraits/men/4.jpg",
    },
    // New fields for PatientHistory
    primaryDiagnosis: "Upper Respiratory Infection",
    pastConditions: ["Sinusitis"],
    allergies: ["Penicillin"],
    medications: ["Decongestant", "Ibuprofen"],
    visits: [
      {
        date: "2024-09-20",
        type: "Check-up",
        doctor: "Dr. John",
        diagnosis: "Upper Respiratory Infection",
        medicationPrescribed: ["Decongestant", "Ibuprofen"],
        notes: "Mild congestion, prescribed decongestant.",
      },
    ],
  },
  {
    id: "P004",
    initials: "AS",
    name: "Anna Smith",
    checkInDate: "2024-10-12",
    disease: "Headache",
    appointmentType: "Consultation",
    mode: "Online",
    date: "2024-10-12",
    time: "01:30 PM",
    town: "Seaside",
    insured: false,
    age: "25",
    sex: "Female",
    education: "Bachelor's Degree",
    occupation: "Designer",
    religion: "Hinduism",
    maritalStatus: "Single",
    assignedDoctor: {
      name: "Dr. Sara",
      image: "https://randomuser.me/api/portraits/women/5.jpg",
    },
    // New fields for PatientHistory
    primaryDiagnosis: "Migraine",
    pastConditions: ["Tension Headaches"],
    allergies: ["Latex"],
    medications: ["Sumatriptan", "Pain Reliever"],
    visits: [
      {
        date: "2024-09-25",
        type: "Consultation",
        doctor: "Dr. Sara",
        diagnosis: "Migraine",
        medicationPrescribed: ["Sumatriptan", "Pain Reliever"],
        notes: "Recommended avoiding triggers, prescribed medication.",
      },
    ],
  },
];
